/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bioinformatica;



import bioinformatica.ultilitarios.Alternativa;
import bioinformatica.ultilitarios.ProdutoDAO;
import static bioinformatica.ultilitarios.ProdutoDAO.getAlternativas;
import static bioinformatica.ultilitarios.ProdutoDAO.getQuestoes;
import static bioinformatica.ultilitarios.ProdutoDAO.setNota;
import static bioinformatica.ultilitarios.ProdutoDAO.usuario;
import bioinformatica.ultilitarios.Questoes;
import bioinformatica.ultilitarios.Usuario;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JFrameQuestao extends javax.swing.JFrame {
private List<Integer> numeros = new ArrayList<Integer>();
private int i = 0;
private Questoes Questoes;
private String strQuestao;
private ArrayList<Alternativa> Alternativa;
private int contCorretos = 0;
private String strLogin;
private int idLogin;

    /**
 * Creates new form JFrameQuestao
     */
    public JFrameQuestao() {
        initComponents();
        strLogin = usuario.getLogin();
        idLogin = usuario.getId();
        sorteia();
        montaQuestao();
        
        labelJogador.setText(strLogin);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rGroupAlternativa = new javax.swing.ButtonGroup();
        labelJogadorRotulo = new javax.swing.JLabel();
        labelJogador = new javax.swing.JLabel();
        labelQuestao = new javax.swing.JLabel();
        btnReponder = new javax.swing.JButton();
        jRadioA = new javax.swing.JRadioButton();
        jRadioB = new javax.swing.JRadioButton();
        jRadioC = new javax.swing.JRadioButton();
        jRadioD = new javax.swing.JRadioButton();
        lblRotuloNumeroQuestao = new javax.swing.JLabel();
        lblRotuloNumeroQuestao1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJogadorRotulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelJogadorRotulo.setText("Jogador:");

        labelJogador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelQuestao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        btnReponder.setText("PROXIMA");
        btnReponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReponderActionPerformed(evt);
            }
        });

        rGroupAlternativa.add(jRadioA);
        jRadioA.setText("A");

        rGroupAlternativa.add(jRadioB);
        jRadioB.setText("B");

        rGroupAlternativa.add(jRadioC);
        jRadioC.setText("C");
        jRadioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCActionPerformed(evt);
            }
        });

        rGroupAlternativa.add(jRadioD);
        jRadioD.setText("D");

        lblRotuloNumeroQuestao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRotuloNumeroQuestao.setText("Questão: ");

        lblRotuloNumeroQuestao1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRotuloNumeroQuestao1.setText("Questão: ");

        btnVoltar.setText("DESISTIR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJogadorRotulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJogador)
                .addGap(182, 182, 182)
                .addComponent(lblRotuloNumeroQuestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRotuloNumeroQuestao1)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioD)
                    .addComponent(jRadioA)
                    .addComponent(jRadioB)
                    .addComponent(jRadioC)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReponder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJogadorRotulo)
                    .addComponent(labelJogador)
                    .addComponent(lblRotuloNumeroQuestao)
                    .addComponent(lblRotuloNumeroQuestao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioA)
                .addGap(18, 18, 18)
                .addComponent(jRadioB)
                .addGap(18, 18, 18)
                .addComponent(jRadioC)
                .addGap(18, 18, 18)
                .addComponent(jRadioD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReponder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReponderActionPerformed
        String strResposta;
        

            
        if(i<20){
            
            if(jRadioA.isSelected() || jRadioB.isSelected() ||  jRadioC.isSelected() || jRadioD.isSelected()){
                
                if(jRadioA.isSelected()){
                    
                    if(Alternativa.get(0).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioB.isSelected()){
                    
                    if(Alternativa.get(1).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioC.isSelected()){
                    
                    if(Alternativa.get(2).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioD.isSelected()){
                    
                    if(Alternativa.get(3).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                
            System.out.println(contCorretos);

            montaQuestao();        // TODO add your handling code here:
            }else{
            JFrame frame = new JFrame("Alerta");
            JOptionPane.showMessageDialog(frame, "Deve ser respondido uma questão!");
                }
        }else if(i==20){
            
            if(jRadioA.isSelected() || jRadioB.isSelected() ||  jRadioC.isSelected() || jRadioD.isSelected()){
                
                if(jRadioA.isSelected()){
                    
                    if(Alternativa.get(0).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioB.isSelected()){
                    
                    if(Alternativa.get(1).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioC.isSelected()){
                    
                    if(Alternativa.get(2).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
                if(jRadioD.isSelected()){
                    
                    if(Alternativa.get(3).isBooResposta()){
                        contCorretos++;
                    }
                    rGroupAlternativa.clearSelection();
                    }
            JFrame frame = new JFrame("Parabens");
            Double nota = (double) 10 / i * contCorretos;

            JOptionPane.showMessageDialog(frame, "A sua nota é: "+nota);     
            System.out.println(contCorretos);
                try {
                    setNota(String.valueOf(idLogin) , String.valueOf(nota));
                    JFrameMenu JFrameMenu = new JFrameMenu();
                    JFrameMenu.setVisible(true);
                    dispose();
                    // TODO add your handling code here:
                } catch (SQLException ex) {
                    Logger.getLogger(JFrameQuestao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            
          
        }
        
    
    }//GEN-LAST:event_btnReponderActionPerformed

    private void jRadioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
int opcao;
           opcao = JOptionPane.showConfirmDialog(null,"Se Você Desistir as Respostas Não Serão Salvas, Tem Certeza? ","Atencão",JOptionPane.YES_NO_OPTION);  
           if(opcao == JOptionPane.YES_OPTION){ 
            JFrameMenu JFrameMenu = new JFrameMenu();
            JFrameMenu.setVisible(true);
            dispose();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameQuestao().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReponder;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JRadioButton jRadioA;
    private javax.swing.JRadioButton jRadioB;
    private javax.swing.JRadioButton jRadioC;
    private javax.swing.JRadioButton jRadioD;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelJogadorRotulo;
    private javax.swing.JLabel labelQuestao;
    private javax.swing.JLabel lblRotuloNumeroQuestao;
    private javax.swing.JLabel lblRotuloNumeroQuestao1;
    private javax.swing.ButtonGroup rGroupAlternativa;
    // End of variables declaration//GEN-END:variables
public void sorteia(){
    //instância um objeto da classe Random especificando a semente
    
    
    for (int i = 1; i <= 20; i++) { //Sequencia da mega sena
        numeros.add(i);
    }
    //Embaralhamos os números:
    Collections.shuffle(numeros);

}
public void montaQuestao(){
            try {
            
            
            
            Questoes = getQuestoes(numeros.get(i));
            strQuestao = Questoes.getQuestao();
            Alternativa = getAlternativas(Questoes.getIdQuestao());
                
            labelQuestao.setText(strQuestao);// seto a questao
            
            //seto as alternativas
            jRadioA.setText("<html>A) "+Alternativa.get(0).getStrAlternativa());
            jRadioB.setText("<html>B) "+Alternativa.get(1).getStrAlternativa());
            jRadioC.setText("<html>C) "+Alternativa.get(2).getStrAlternativa());
            jRadioD.setText("<html>D) "+Alternativa.get(3).getStrAlternativa());
                
            i++;
                for(int i=0; i<4;i++){
                    if(Alternativa.get(i).isBooResposta()){
                        System.out.println(Alternativa.get(i).getStrAlternativa());
                    }
                }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrameQuestao.class.getName()).log(Level.SEVERE, null, ex);
        }
            lblRotuloNumeroQuestao1.setText(String.valueOf(i));
}
    
}

